/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcq_180107;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author albert
 */
public class AdminUser extends javax.swing.JFrame {
    
   int operation =0;
   int row=0;
   String userId="";
    /**
     * Creates new form AdminUser
     */
    public AdminUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        reset();
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtUser = new javax.swing.JTextField();
        txtToken = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin | User");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Token"
            }
        ));
        table.setShowVerticalLines(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        txtToken.setEditable(false);

        jLabel1.setText("Username");

        jLabel2.setText("Token");

        btnGenerate.setLabel("Generate Token");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnSave.setLabel("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Add New");
        btnClear.setToolTipText("");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("User Control");

        lblInfo.setForeground(new java.awt.Color(204, 0, 51));
        lblInfo.setText("jLabel4");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser)
                            .addComponent(txtToken)
                            .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String token=tokenGenerator();
        txtToken.setText(token);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        
        btnDelete.setEnabled(true);
        operation=1;
        
      // code to set selected value on form
       
        int column = table.getColumnCount();
         row = table.getSelectedRow();
        
         if(row>=0)
         {
           btnDelete.setEnabled(true);   
         }
         
        lblInfo.setText("Update or Delete the user"+ table.getModel().getValueAt(row,1).toString());
//         String value = table.getModel().getValueAt(row,0).toString();
        userId=table.getModel().getValueAt(row,0).toString();
        txtUser.setText(table.getModel().getValueAt(row,1).toString());
        txtToken.setText(table.getModel().getValueAt(row,2).toString());
        
       
        
      
    }//GEN-LAST:event_tableMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(operation==1){
            Connection con= Connect.getConnection();
            boolean chk=true;
            try {
                chk=checkUser(userId,txtUser.getText());
            } catch (SQLException ex) {
                Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            System.out.println(chk);
            if(checkField()){
                if (chk){
                JOptionPane.showMessageDialog(null, "Username already taken. Please choose another username.", "Error", JOptionPane.ERROR_MESSAGE);
		return;		
                }
                else{
                   try {

                    PreparedStatement pst= con.prepareStatement("update  users set username=?,password=? where id=?");
                    pst.setString(1, txtUser.getText());
                    pst.setString(2, txtToken.getText());

                    pst.setString(3, userId);
                    pst.executeUpdate();




                    } catch (SQLException ex) {
                      Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                      ex.printStackTrace();


                    }
                    DefaultTableModel model = (DefaultTableModel) table.getModel();

                    model.setValueAt(userId, row, 0);
                    model.setValueAt(txtUser.getText(), row, 1);
                    model.setValueAt(txtToken.getText(), row, 2);
                    JOptionPane.showMessageDialog(null, "Successfully updated", "Updated", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    return;
                }
            }else return;
            
            
//       
            
        }
        else{
            if(checkField()){
                boolean chk=true;
                try {
                    chk=checkUserDup(txtUser.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
                System.out.println(chk);
                if (chk){
                    JOptionPane.showMessageDialog(null, "Username already taken. Please choose another username.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;		
                }else{
                    Connection con= Connect.getConnection();
                    PreparedStatement pst;
                    try {
                        pst = con.prepareStatement("insert into users (username,password,is_admin) values (?,?,?)");
                        pst.setString(1, txtUser.getText());
                        pst.setString(2, txtToken.getText());
                        pst.setString(3, "0");
                        pst.execute();

                    } catch (SQLException ex) {
                        Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                        return;
                    }
                    ResultSet rs;
                    int last_inserted_id=0;
                    try {
                        rs = pst.getGeneratedKeys();
                        if(rs.next())
                        {
                            last_inserted_id = rs.getInt(1);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    model.addRow(new Object[]{last_inserted_id, txtUser.getText(), 
                    txtToken.getText()}); 
                    JOptionPane.showMessageDialog(null, "User Added Successfully", "Added", JOptionPane.INFORMATION_MESSAGE);
                    reset();
                    return;


                }
            }
            
        }
            
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(operation==0)
        {
            JOptionPane.showMessageDialog(null, "No user selected to delete. Please Select any users", "Delete", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to delete this user?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
              // Saving code here
                Connection con= Connect.getConnection();
                PreparedStatement pst = null;
                try {
                    pst = con.prepareStatement("delete from users where id=?");

                    pst.setString(1, userId);
                    pst.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
                JOptionPane.showMessageDialog(null, "User Deleted", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.removeRow(row);
                reset();
                return;
            }
            return;
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminDash ad= new AdminDash();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void reset()
    {
        lblInfo.setText("Please fill up the form to add new user");
        userId="";
        txtUser.setText("");
        txtToken.setText("");
        operation=0;
        btnDelete.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUser().setVisible(true);
            }
        });
    }
    
    boolean checkUser(String id,String username) throws SQLException{
           ResultSet rs;
           rs = Connect.getResult("select * from users where id <>"+id+" AND username='"+username+"' ");
           return (rs.next());
    }
    
    boolean checkUserDup(String username) throws SQLException{
        ResultSet rs;
        rs = Connect.getResult("select * from users where username='"+username+"' ");
        return (rs.next());
    }
    
    boolean checkField(){
        if(txtUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;	 
        }
        if(txtToken.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please generate token before saving", "Error", JOptionPane.ERROR_MESSAGE);
            return false;	 
        }
        return true; 
    }
    
    void loadData()
    {
        
       try {
           ResultSet rs;
           rs = Connect.getResult("select * from users where is_admin =0");
           DefaultTableModel model = (DefaultTableModel) table.getModel();
           while(rs.next())
           {
            model.addRow(new Object[]{rs.getString(1), rs.getString(2), 
            rs.getString(3)});
               
           }
           
           
           
           
 
           
       } catch (SQLException ex) {
           Logger.getLogger(AdminUser.class.getName()).log(Level.SEVERE, null, ex);
           ex.printStackTrace();
       }
        
    }

    public String tokenGenerator()
    {
        String charList = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvxyz"; 

    StringBuilder token = new StringBuilder(6); 

    for (int i = 0; i < 6; i++) { 

        int index 
            = (int)(charList.length() * Math.random()); 

        token.append(charList.charAt(index)); 
    } 

    return token.toString(); 

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
