/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcq_180107;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DecimalFormat;

/**
 *
 * @author albert
 */
public class MCQ_Exam extends javax.swing.JFrame {
    int count=0;
    int index=0;
    int total=0;
    String selected="";
    String qId="4";
    String userId="";
    String user="";
    ResultSet rs;
    ResultSet tmp=null;
    String[] inputAnswer;
    String[] correctAnswer;
    
    /**
     * Creates new form MCQ_Exam
     */
    public MCQ_Exam() throws SQLException {
        
        
        
        
    }
    
    public void setVar(String i,String u,String uid) throws SQLException
    {
        this.qId=i;
        this.user=u;
        this.userId=uid;
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        init();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnSubmit = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        rdA1 = new javax.swing.JRadioButton();
        rdA2 = new javax.swing.JRadioButton();
        rdA3 = new javax.swing.JRadioButton();
        rdA4 = new javax.swing.JRadioButton();
        lblQno = new javax.swing.JLabel();
        lblQS = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User | MCQ Exam");
        setResizable(false);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnPrev.setText("Previous");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblQuestion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblQuestion.setText("Question Name");

        rdA1.setText("jRadioButton1");
        rdA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdA1ActionPerformed(evt);
            }
        });

        rdA2.setText("jRadioButton1");
        rdA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdA2ActionPerformed(evt);
            }
        });

        rdA3.setText("jRadioButton1");
        rdA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdA3ActionPerformed(evt);
            }
        });

        rdA4.setText("jRadioButton1");
        rdA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdA4ActionPerformed(evt);
            }
        });

        lblQno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblQno.setText("Q no:");

        lblQS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblQS.setText("Question Set");

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotal.setText("Total:");

        btnBack.setText("Return");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Logged in as:");

        lblUser.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUser))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblQno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdA3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdA4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(lblQS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQno)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdA3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdA4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnPrev)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to submit?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            for(int i =0;i<count;i++){
                if(inputAnswer[i]!=null && inputAnswer[i].equals(correctAnswer[i])){
                    total+=1;
                }
            }

            DecimalFormat df = new DecimalFormat("#.##");
            double p=((double)total/count)*100;
            Connection con= Connect.getConnection();
            String result= p>=40 ? "Pass" : "Fail";
            
            try {
                ResultSet rs=Connect.getResult("select * from reports where user_id="+userId+" AND question_set_id="+qId+"");
                if(!rs.next())
                {
                    PreparedStatement ps= con.prepareStatement("insert into reports (user_id,question_set_id,total_question,correct_answer,percentage,result) values(?,?,?,?,?,?)");
                    ps.setString(1, userId);
                    ps.setString(2, qId);
                    ps.setInt(3, count);
                    ps.setInt(4, total);
                    ps.setString(5, df.format(p));
                    ps.setString(6, result);
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null, "Total Questions:"+ count +"\nCorrect Answers:"+total+"\nPercentage:"+df.format(p), "Result", JOptionPane.INFORMATION_MESSAGE);
                    UserDash ud=new UserDash();
                    ud.setVar(this.user,this.userId);
                    ud.setVisible(true);
                    dispose();
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Already Submitted", "Warning", JOptionPane.WARNING_MESSAGE);
            
                }
            } catch (SQLException ex) {
                Logger.getLogger(MCQ_Exam.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            total=0;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(rs.previous())
            {
                index-=1;
                setPage(rs);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MCQ_Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            // TODO add your handling code here:
            if(rs.next())
            {
                index+=1;
                setPage(rs);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MCQ_Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void rdA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdA1ActionPerformed
        // TODO add your handling code here:
        selected="a";
        inputAnswer[index]=selected;
        System.out.println(selected);
        
    }//GEN-LAST:event_rdA1ActionPerformed

    private void rdA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdA2ActionPerformed
        // TODO add your handling code here:
        selected="b";
        
        inputAnswer[index]=selected;
        System.out.println(selected);
    }//GEN-LAST:event_rdA2ActionPerformed

    private void rdA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdA3ActionPerformed
        // TODO add your handling code here:
        selected="c";
        
        inputAnswer[index]=selected;
        System.out.println(selected);
    }//GEN-LAST:event_rdA3ActionPerformed

    private void rdA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdA4ActionPerformed
        // TODO add your handling code here:
        selected="d";
        
        inputAnswer[index]=selected;
        System.out.println(selected);
    }//GEN-LAST:event_rdA4ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            // TODO add your handling code here:
            UserDash ud=new UserDash();
            ud.setVar(this.user,this.userId);
            ud.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MCQ_Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MCQ_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MCQ_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MCQ_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MCQ_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MCQ_Exam().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MCQ_Exam.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void init() throws SQLException{
        lblUser.setText(this.user);
        btnGroup.add(rdA1);
        btnGroup.add(rdA2);
        btnGroup.add(rdA3);
        btnGroup.add(rdA4);
        
        ResultSet qs = Connect.getResult("select title from question_sets where id="+qId+"");
        if(qs.next())
        {
            lblQS.setText(qs.getString("title"));
        }
        rs = Connect.getResult("select * from questions where question_set_id="+qId+"");
        tmp = Connect.getResult("select * from questions where question_set_id="+qId+"");
        ResultSet rc=Connect.getResult("select count(*) from questions where question_set_id="+qId+"");
        if(rc.next()){
            count=rc.getInt(1);
            inputAnswer=new String[count];
            correctAnswer=new String[count];
        }
//        setting correct answer
        lblTotal.setText("Total: "+count);
        int counter=0;
        while(tmp.next()){
            correctAnswer[counter]=tmp.getString("correct_answer");
            counter+=1;
             System.out.println(tmp.getString("correct_answer"));
        }
        
        if(!rs.next()){
            JOptionPane.showMessageDialog(null, "There are no question in this set. Closing", "Result", JOptionPane.ERROR_MESSAGE);
            
//            dispose();
            return;
        }else{
            setPage(rs);
//            System.out.println(rs.getString(1));
            
        }
    }
    public void setPage(ResultSet r) throws SQLException{
        btnGroup.clearSelection();
        lblQno.setText("Q no: "+(index+1));
        lblQuestion.setText(r.getString("question"));
        rdA1.setText(r.getString("answer_1"));
        rdA2.setText(r.getString("answer_2"));
        rdA3.setText(r.getString("answer_3"));
        rdA4.setText(r.getString("answer_4"));
        tmp.last();
        int cur=rs.getInt("id");
        
        int last=tmp.getInt("id");
        tmp.first();
        
        int first=tmp.getInt("id");
        if(cur==last){
           btnNext.setEnabled(false); 
        }else{
           btnNext.setEnabled(true); 
        }
        if(cur==first){
            btnPrev.setEnabled(false);
        }else{
            btnPrev.setEnabled(true);
        }
        
        for(int i =0;i<inputAnswer.length;i++){
            System.out.println(inputAnswer[i] + "   "+ correctAnswer[i]);
        }
        
        if(inputAnswer[index]!=null){
            switch (inputAnswer[index]){
                    case "a":
                        rdA1.setSelected(true);
                        break;
                    case "b":
                        rdA2.setSelected(true);
                        break;
                    case "c":
                        rdA3.setSelected(true);
                        break;
                    case "d":
                        rdA4.setSelected(true);
                        break;
                    default:
                        break;            
            }
                        
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQS;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JRadioButton rdA1;
    private javax.swing.JRadioButton rdA2;
    private javax.swing.JRadioButton rdA3;
    private javax.swing.JRadioButton rdA4;
    // End of variables declaration//GEN-END:variables
}
